### ISSUE TITLE
Clientside imports with relative path ../ are broken

### ISSUE THREAD

**Issue by FlorianV85** [altmp/altv-js-module-v2#103]
Imports with a relative path ``../`` are broken on clientside.

```console
[19:17:14][Error] [JS] Failed to instantiate file client/client.js
[19:17:14][Error] [JS] SyntaxError: The requested module '../myDogs/dogs.js' does not provide an export named 'dog'
[19:17:14][Error] Failed to load resource main
```

### Reproduction

I then created this minimalist resource to test and reproduce the issue.

1. Create a client resource with this structure :
![ss+(2023-09-25+at+07 21 33)](https://github.com/altmp/altv-js-module-v2/assets/15657365/88339a70-ae54-4ed5-baf8-b1bb05b0685e)
2. In **client.js**
```js
import * as alt from '@altv/client';
import './animals/animal.js';
alt.log('client loaded');
```
3. In **myDogs/dogs.js**
```js
export function dog() {
    return 'CrazyDog';
}
```
4. In **animals/animal.js**
```js
import * as alt from '@altv/client';
import { dog } from '../myDogs/dogs.js';
alt.log(`My dog is ${dog()}`);
```
5. The import ``import { dog } from '../myDogs/dogs.js';`` causes error in animals/animal.js, but works well with absolute path.

I tested this same resource on v1 module and it works. The console tells me my dog is CrazyDog.

**Comment by LeonMrBonnie** [comment]
fixed
