### ISSUE TITLE
Serverside: setPlayerFactory breaks alt.Player.all

### ISSUE THREAD

**Issue by FlorianV85** [altmp/altv-js-module-v2#107]
Once Player Factory is set, ``alt.Player.all`` array is broken and is always empty.

```js
import * as alt from '@altv/server';

class PlayerFactory extends alt.Player {
    myMethod() {
        return 'my method';
    }
}

alt.Factory.setPlayerFactory(PlayerFactory); 

alt.Events.onPlayerConnect(({ player }) => {
    player.model = 0x9C9EFFD8;
    player.spawn(new alt.Vector3(447.032, 5645.732, 750));
    alt.log(`${player.name} connected`);
    
    alt.log(alt.Player.all.length); // Return always 0 if Player Factory is set
});
```

**EDIT :** 
``PlayerFactory.all`` also returns an empty array.

**EDIT 2 :** 
Tested with Vehicle and same issue. The problem seems to apply to all factories.

**Comment by Yiin** [comment]
does `PlayerFactory.all` work?

**Comment by FlorianV85** [comment]
> does `PlayerFactory.all` work?

No, return also ``0``

**Comment by LeonMrBonnie** [comment]
Only for players or does this also apply to e.g. alt.Vehicle?

**Comment by FlorianV85** [comment]
> Only for players or does this also apply to e.g. alt.Vehicle?

I've just tested it with Vehicle and the issue seems to apply there too.
