### ISSUE TITLE
RPC events crashing the server are back with latest commits

### ISSUE THREAD

**Issue by FlorianV85** [altmp/altv-js-module-v2#116]
> Fixed in [7fbac53](https://github.com/altmp/altv-js-module-v2/commit/7fbac53b2e6c69106b4751f6138ba49a7dd29a10) - re-test with `dev/0.0-dev29` or later

I've built with the latest commits and it's still crashing. But works well with the latest release. Thinks it's been broken again in the new commits 👀

_Originally posted by @FlorianV85 in https://github.com/altmp/altv-js-module-v2/issues/115#issuecomment-1742129268_

**Comment by LeonMrBonnie** [comment]
fixed in 30b4fd17f3c783c2bb86220735e01d45f5c5bca1
