### ISSUE TITLE
v2 doesnt like v1

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module-v2#12]
![изображение](https://user-images.githubusercontent.com/54737754/235158621-f0b2a8a0-5715-4dad-bf48-2c23422dcf3c.png)

server config:

![изображение](https://user-images.githubusercontent.com/54737754/235158639-e8fe209a-60f2-4a26-921a-38da027fe02a.png)

**Comment by LeonMrBonnie** [comment]
its fixed, v2 uses a different binary name for nodejs now
