### ISSUE TITLE
onWorldObjectStreamIn/Out undefined object

### ISSUE THREAD

**Issue by notmatical** [altmp/altv-js-module-v2#144]
create a virtual entity group and add a virtual entity on the server, on the client make a onWorldObjectStreamIn/Out event and log the entity, it will be undefined

**Comment by Yiin** [comment]
can't reproduce

![image](https://github.com/altmp/altv-js-module-v2/assets/9081457/74597bf2-b9d9-4669-8bdc-f7521fd010d3)
![image](https://github.com/altmp/altv-js-module-v2/assets/9081457/ef9c3149-060d-4eb5-b575-fa60ec2f60af)
![image](https://github.com/altmp/altv-js-module-v2/assets/9081457/c5dd68c6-fb33-4351-8edc-20affceab479)

**Comment by xxshady** [comment]
@Yiin just so you know, `typeof null` is also 'object' and you can just pass `object` to `alt/console.log`, it will output you constructor name of it

**Comment by Yiin** [comment]
fuck right I forgot

**Comment by xLuxy** [comment]
@notmatical please provide reproduction sample - i can't reproduce using the following:

###Server:
```js
import * as alt from "@altv/server";

const virtualEntityGroup = alt.VirtualEntityGroup.create({
  maxEntitiesInStream: 128,
});

for (let i = 0; i < 10; ++i) {
  const VirtualEntity = alt.VirtualEntity.create({
    group: virtualEntityGroup,
    pos: { x: 0, y: 0, z: i * 0.5 },
    streamingDistance: 100,
  });

  VirtualEntity.streamSyncedMeta.customId = i;
}

alt.Events.onPlayerConnect(({ player }) => {
  player.model = "mp_m_freemode_01";
  player.spawn({ x: 0, y: 0, z: 71 });
});
```

###Client:
```js
import * as alt from "@altv/client";

alt.Events.onWorldObjectStreamIn(({ object }) => {
  if (!(object instanceof alt.VirtualEntity)) return;

  const customId = object?.streamSyncedMeta?.customId;
  alt.log(
    `VirtualEntity with customId ${customId} streamed in - remoteid: ${object.remoteID}`
  );
});

alt.Events.onWorldObjectStreamOut(({ object }) => {
  if (!(object instanceof alt.VirtualEntity)) return;

  const customId = object?.streamSyncedMeta?.customId;
  alt.log(
    `VirtualEntity with customId ${customId} streamed out - remoteId: ${object.remoteID}`
  );
});
```

![image](https://github.com/altmp/altv-js-module-v2/assets/67131061/01e91221-d532-4823-85dd-921571c7815b)
![GTA5_QvmKET99rk](https://github.com/altmp/altv-js-module-v2/assets/67131061/07693b91-fd84-4c7f-88cf-e98f4320afe1)

**Comment by xLuxy** [comment]
Feel free to re-open once reproduction has been provided.
