### ISSUE TITLE
``typeof player.socialID`` doesn't return a ``bigint``, but a ``number``

### ISSUE THREAD

**Issue by FlorianV85** [altmp/altv-js-module-v2#149]
```js
alt.log(typeof player.socialID)
```

Returns a ``number``, when it should return a ``bigint``

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/b79807b10e481de1ab1066138e8a3ea5d14e7dd3 - will be available with next NPM release

**Comment by FlorianV85** [comment]
> Fixed in [b79807b](https://github.com/altmp/altv-js-module-v2/commit/b79807b10e481de1ab1066138e8a3ea5d14e7dd3) - will be available with next NPM version

@xLuxy In case the information is useful, I saw that you had also changed the type of ``hwidHash``, but ``typeof hwidHash`` did return ``bigint``!

![ebf01dce47 1](https://github.com/altmp/altv-js-module-v2/assets/15657365/76bdcf83-cd4f-447a-9233-ad0f86a1e72d)

**Comment by xLuxy** [comment]
Fixed @FlorianV85, kinda feel like it should be `number | bigint` because sometimes it might be numeric i think.
