### ISSUE TITLE
``Vehicle.driver`` clientside always return ``null``

### ISSUE THREAD

**Issue by FlorianV85** [altmp/altv-js-module-v2#150]
On clientside, ``Vehicle.driver`` always return ``null``. Tested serverside and works well.

**Reproduction:**

1. Create a vehicle serverside
2. Call ``vehicle.driver`` clientside. For example in an event like:
```js
alt.Events.onPlayerVehicleEntered(({ vehicle, seat }) => {
    alt.log('seat', seat);
    alt.log(vehicle.driver);
});

alt.Events.onPlayerVehicleLeft(({ vehicle, seat }) => {
    alt.log('seat', seat);
    alt.log(vehicle.driver);
});
```

**Comment by LeonMrBonnie** [comment]
Does it work in v1? Its the same code for client and server, it just calls a SDK method so I think its an SDK issue

**Comment by FlorianV85** [comment]
> Does it work in v1? Its the same code for client and server, it just calls a SDK method so I think its an SDK issue

Hmmm, yes. In v1, ``driver`` returns ``undefined``.

**Comment by FlorianV85** [comment]
Issue opened in altv-issues repository https://github.com/altmp/altv-issues/issues/2115

**Comment by LeonMrBonnie** [comment]
I assume it just isn't implemented for client yet and just a placeholder. I won't remove it for now hoping it will get fixed
