### ISSUE TITLE
RML elements are not properly registered

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-js-module-v2#164]
v1:
```ts
import * as alt from 'alt-client';

const document = new alt.RmlDocument("/client/index.rml");

alt.log("Container", !!document.getElementByID("container"));
```
```
Container true
```

v2:
```ts
import * as alt from '@altv/client';

const document = alt.RmlDocument.create({ url: "/client/index.rml" });

alt.log("Container before delay", !!document.getElementByID("container"));

alt.Timers.nextTick(() => {
	alt.log("Container after delay", !!document.getElementByID("container"));
});

alt.Timers.setTimeout(() => {
	alt.log("Container after 1s delay", !!document.getElementByID("container"));
}, 1000);
```

```
Container before delay false 
Loaded resource test-resource 
Container after delay false 
Container after 1s delay false 
```

`document.createElement` also returns `null`.

index.rml:
```html
<rml>
  <head>
    <title>RMLUI</title>
  </head>
  <body id="container"></body>
</rml>
```

**Comment by Yiin** [comment]
document itself is valid object
![image](https://github.com/altmp/altv-js-module-v2/assets/118209451/84e486d0-f630-4521-b62f-8d926a0e1173)

but it's innerRML returns empty string (should be content of index.rml).

**Comment by xLuxy** [comment]
This has to be fixed by alt:V - see https://github.com/altmp/altv-issues/issues/2209

**Comment by xLuxy** [comment]
I temporarily added a workaround for ScriptObjects not being created for RmlElements, however, the real fix has to come from alt:V

Once alt:V fixes this, revert the following Pull Request: https://github.com/altmp/altv-js-module-v2/pull/167

**Comment by xLuxy** [comment]
On latest `dev` Version, `OnCreateBaseObject` method receives `nullptr` when creating an `RmlDocument`. (Basically logging the type inside the methods):
Crashdump Id: 631f276d-858b-4d88-a4e2-3cf88a2a2087
