### ISSUE TITLE
alt.Checkpoint constructor doesn't match typings (v1 compat)

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module-v2#179]
(Serverside) `const c = new alt.Checkpoint(0, 0, 0, 0, 10, 10, 0, 0, 0, 0, 100)` results in:

![image](https://github.com/altmp/altv-js-module-v2/assets/54737754/838f89e6-a270-4989-9b35-bcda4408d5ce)

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/82de99994d682aac812c2bfe178a3c80967c0fe7 using the following code:
```js
import altOld from 'alt-server';

const c = new altOld.Checkpoint(0, 0, 0, 0, 10, 10, 0, 0, 0, 0, 100);
alt.log('checkpint 1', c);

const c2 = new altOld.Checkpoint(0, { x: 0, y: 0, z: 0 }, 10, 10, new altOld.RGBA(255, 157, 0, 255), 100);
alt.log('checkpint 2', c2);
```
