### ISSUE TITLE
resourceError event doesn't work as it was in v1

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module-v2#188]
## code

```js
import alt from 'alt-server'
alt.on('resourceError', (...args) => {
  alt.log('resourceError', args)
})

alt.setTimeout(() => {
  throw new Error('test')
}, 500)
```

## v1

![image](https://github.com/altmp/altv-js-module-v2/assets/54737754/e621a4e6-9119-450e-a9e8-c2fcd40c0c8f)

## v2 (v1 compat)

![image](https://github.com/altmp/altv-js-module-v2/assets/54737754/f1b29c18-aa51-44cb-bbe5-63301217b23d)

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/3ef9644208d11d82b67a23f4bf18e0b55c5d93c0 - if you find anything missing feel free to re-open

**Comment by xxshady** [comment]
@xLuxy 

line is incorrect, in v1 it shows exact line of throw, in v2 it shows line where closure is defined

![image](https://github.com/altmp/altv-js-module-v2/assets/54737754/c4e3716f-a9fc-40ce-9e4d-474a01f7eb00)
