### ISSUE TITLE
typeof value == "object"

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module-v2#189]
doesn't make sense because `typeof null` is "object"

![image](https://github.com/altmp/altv-js-module-v2/assets/54737754/c5e21824-9a3c-4956-831b-aa38603dc301)

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/2fa84f8aa774c7d6fe33b58bad94ba07626853cb - thanks for reporting :)
