### ISSUE TITLE
ResourceStop at serverside should handle promise

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module-v2#193]
Both in v2 API and compatibility

this code works in v1:
```js
alt.on('resourceStop', async () => {
  await alt.Utils.wait(1000)
})
```

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/7c3e25dc6424c5d8a2ccffa5091e436d9676353b - will be available on next module release.
