### ISSUE TITLE
`alt.File.read` is implemented incorrectly

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module-v2#201]
see: https://github.com/altmp/altv-js-module/blob/dev/shared/bindings/File.cpp#L26

**Comment by xLuxy** [comment]
This seems to be a Core issue since it's also not working with the same code as in v1 - it throws an warning message which comes directly from core:

![img](https://i.imgur.com/8VhkIzz.png)

**Comment by xLuxy** [comment]
Fixed in `dev/0.0.0-dev.27`
