### ISSUE TITLE
(Serverside) vehicle.neon not writable

### ISSUE THREAD

**Issue by devpanda0** [altmp/altv-js-module-v2#207]
vehicle.neon is readonly
![image](https://github.com/altmp/altv-js-module-v2/assets/49129501/54e5d12f-b1cf-4c25-8b57-78c6c3b97e28)

**Comment by xLuxy** [comment]
Hey there,

this behavior won't change - however, i introduced 2 new methods in `dev/0.0.0-dev.33` which should help you with this:
```ts
const vehicle: alt.Vehicle;

vehicle.getNeonActive(): alt.VehicleNeonState
vehicle.setNeonActive(states: Partial<alt.VehicleNeonState>)
```
