### ISSUE TITLE
`getSyncedMeta` / `hasSyncedMeta` crashing client & server

### ISSUE THREAD

**Issue by ToffyMTA** [altmp/altv-js-module-v2#209]
Calling `getSyncedMeta` or `hasSyncedMeta` is leading to a game / server crash.

**Example resource:**
[test.zip](https://github.com/altmp/altv-js-module-v2/files/14900257/test.zip)

**Comment by xLuxy** [comment]
Should be fixed with latest build - however, Virtual Entity will still crash when trying to access syncedMeta - will need to investigate further why `syncedMeta` property always seems to pick up the one from VirtualEntity class.
