### ISSUE TITLE
(compat, client) TextDecoder implementation is wrong?

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module-v2#211]
Emojis are decoded incorrectly:
![image](https://github.com/altmp/altv-js-module-v2/assets/54737754/41b7b1f7-1d50-4b8d-b0e6-a9f89d339396)

repro: https://github.com/xxshady/altv-esbuild-rust-wasm/blob/b5e8318a4ceff63a3f36dd98388af6b9486f6383/example/dist.js

with [this polyfill](https://github.com/xxshady/altv-esbuild-rust-wasm/blob/b5e8318a4ceff63a3f36dd98388af6b9486f6383/text-encoder/polyfill.js) it works correctly tho
![image](https://github.com/altmp/altv-js-module-v2/assets/54737754/e2f43268-fef0-46b3-9f72-f6b0156ad000)

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/16e7c685b40d7821a3861f72ba3381e893acab70
