### ISSUE TITLE
[Feature Request]: Add the possibility to give entities an initial streamSyncedMeta data

### ISSUE THREAD

**Issue by devpanda0** [altmp/altv-js-module-v2#215]
It is meant as with the VirtualEntity that you can specify initial streamSyncedMeta Data. It would be nice if this were available for everyone, where you can also set streamSyncedMeta

**Comment by xLuxy** [comment]
Added in https://github.com/altmp/altv-js-module-v2/commit/6b0ea967a0c188828f99945401eaa95e6a5af44c
