### ISSUE TITLE
`toArray()` for Vectors seems unimplemented, but it exists in types

### ISSUE THREAD

**Issue by wh1tevs** [altmp/altv-js-module-v2#231]
https://github.com/altmp/altv-js-module-v2/blob/63291f80fac1665bb10c770c57017ec890e4b30c/types/shared/index.d.ts#L169-L181

```
[20:43:04][Error] TypeError: vec2.toArray is not a function
   ...stacktrace
```
```
[20:44:35][Error] TypeError: vec3.toArray is not a function
   ...stacktrace
```

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/028d7e13ca1ec65ce2ea018008711f13e27241c7 - thank you for reporting. Build `dev/0.0.0-dev.45` has been triggered with this fixed.
