### ISSUE TITLE
V8 exception not visible when thrown from top level

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module-v2#242]
```js
import alt from '@altv/server'

alt.Events.on('test', (...data) => {
  alt.log({ data })
})

// abusing magic bytes to create v8 exception
// not visible (but its still fails at deserialization)
alt.Events.emit('test', new Uint8Array([74, 83, 86, 97, 108]).buffer)

setTimeout(() => {
  // this one is visible
  // Error: Unable to deserialize cloned data due to invalid or unsupported version
  alt.Events.emit('test', new Uint8Array([74, 83, 86, 97, 108]).buffer)
}, 100)
```

**Comment by xLuxy** [comment]
I cannot reproduce on latest dev version - feel free to re-open with additional info when it re-occurs.

[<img src="https://i.imgur.com/0uGx4mR.png" />]

**Comment by xxshady** [comment]
also happens on client

**Comment by xxshady** [comment]
probably this is where exception is thrown: https://github.com/altmp/altv-js-module-v2/blob/f29df54587bdeea608d9948fa603c46cc69fac8f/shared/src/helpers/ValueBuffer.cpp#L413

**Comment by xLuxy** [comment]
can't reproduce on server:

<img src="https://i.imgur.com/uaEwZJ6.png" />
