### ISSUE TITLE
TODO: investigate

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module-v2#247]
```js
import alt from '@altv/server'

alt.Vehicle.create({
  model: 'sultan',
  pos: new alt.Vector3(0),
  initialMeta: {
    syncedMeta: 1,
  }
})
```

why it throws "expected Invalid"
`Error: Invalid argument type at index 0, expected Invalid but got number`

**Comment by xLuxy** [comment]
Cannot reproduce with the following code snippet aswell as the snippet provided above using the latest build (`dev/0.0.0-dev.50`)

```js
import alt from '@altv/server';

const veh = alt.Vehicle.create({
  model: 'sultan',
  pos: new alt.Vector3(0),
  initialData: {
    syncedMeta: 1,
  },
});

alt.log(veh.syncedMeta.a);
```

**Comment by xxshady** [comment]
@xLuxy i dont really remember but i think it throwed it in my branch, from which i wanted to create PR (initial metadata)

try this:
```js
vehicle.setMultipleSyncedMetaData(1)
```

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/788aba6dc1541438c97a701b7f0b85c66e26cf99 - will e available with next build.
