### ISSUE TITLE
Is it typo?

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module-v2#249]
https://github.com/altmp/altv-js-module-v2/blob/c4ecabb9ca18f03deb8fa846e056fd6ef61ea008/shared/js/entityUtils.js#L48

**Comment by xLuxy** [comment]
In that case, most likely. When writing that i mainly copy pasted as you can see below. Feel free to fix.

**Comment by xLuxy** [comment]
Should be fine with https://github.com/altmp/altv-js-module-v2/commit/244a262ffbe5d3334a258e2b47a83f49de2d3d95
