### ISSUE TITLE
`onVoiceConnectionUpdate` "event" / function is missing

### ISSUE THREAD

**Issue by shloooo** [altmp/altv-js-module-v2#251]
As the title says, the method for `onVoiceConnectionUpdate` is missing in the module.
It is already included in the typings, but you cannot use it because the method is missing in the module itself.

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/fe6aa12b27a1e644d37ed66d0793dff5e2c4e3c5 - the event is now named `onVoiceConnectionStateChange` / `onceVoiceConnectionStateChange` and is available with `dev/0.0.0-dev.50`
