### ISSUE TITLE
(compat, client) ``alt.FocusData.overrideFocus`` does not work.

### ISSUE THREAD

**Issue by ToffyMTA** [altmp/altv-js-module-v2#252]
![vrfa4w8JBV](https://github.com/user-attachments/assets/a087d60c-1e49-40c6-b11e-7bb7dbbf5cac)

```js
import alt from 'alt-client';
alt.FocusData.overrideFocus(new alt.Vector3(954, 15, 130));
```

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/b559b93366da75be04ec44cc10f2c020126817c1 (>= `dev/0.0.0-dev.53`)
