### ISSUE TITLE
Don't use Date for things where elapsed time is needed

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module-v2#255]
We need to refactor `Date` uses, for example [here](https://github.com/altmp/altv-js-module-v2/blob/20b0d4f7b6bb6fba053e2bacb824faa1f4312287/shared/js/timers.js#L89), because player can [change](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#performance.now_vs._date.now) their local time and then everything will break

We should probably use net time for it instead

**Comment by xLuxy** [comment]
Replaced with net time in https://github.com/altmp/altv-js-module-v2/commit/82fe74e1231c3893cd640af2295c0f16d6cfdcd0
