### ISSUE TITLE
`new TextEncoder()` doesn't work

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module-v2#258]
```js
// clientside
new TextEncoder("utf-8") 
```

throws `Error: Use alt.*.create() to create an instance of this class`

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/8463b3adce8efbaa01f506d3507522320df81d63.

The encoding argument is being ignored for now because we only support UTF-8 at the moment.
