### ISSUE TITLE
Missing server events

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-js-module-v2#66]
v1 server events that are missing from v2:

- [x] anyResourceError
- [x] anyResourceStart
- [x] anyResourceStop
- [ ] removeEntity
- [x] vehicleHorn
- [x] vehicleSiren
- [ ] playerSpawn
- [x] metaChange
- [x] voiceConnection
- [x] clientDeleteObject
- [ ] clientRequestObject

**Comment by xLuxy** [comment]
`vehicleSiren` -> `alt.Events.onVehicleSiren`
`voiceConnection` => `alt.Events.VoiceConnection`
`metaChange` => `alt.Events.onGlobalMetaChange`
`anyResourceStart` => `alt.Events.onResourceStart`
`anyResourceStop` => `alt.Events.onResourceStop`
`anyResourceError` => `alt.Events.onResourceError`

`removeEntity` won't be added as `onBaseObjectCreate` and `onBaseObjectRemove` replaces them

The rest will be added soon.

**Comment by xLuxy** [comment]
The following events were added in https://github.com/altmp/altv-js-module-v2/commit/f8871ef2be93c5af10207851a9133b9eb5988cd9

`clientDeleteObject` => `onClientObjectDelete`
`clientRequestObject` => `onClientObjectRequest`
`playerSpawn` => `onPlayerSpawn`
`vehicleHorn` => `onVehicleHornStateChange`
