### ISSUE TITLE
Custom events can't be typed based on event name anymore.

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-js-module-v2#67]
e.g. on server using v1, you can type custom events such as 
```
alt.on(eventName, cb)
alt.onClient(eventName, cb)
```
By extending `shared.ICustomClientServerEvent` interface. It's not possible anymore as eventKey is merged into handler properties.

Script events such as `alt.onServerScriptEvent`, `alt.onClientScriptEvent` should provide the ability to define `<T>` typings based on `eventName: T`.

**Comment by xLuxy** [comment]
Added in https://github.com/altmp/altv-js-module-v2/commit/bd31418f344ebf96b23492154087b4c4548a753a
