### ISSUE TITLE
vector arguments should accept IVector type instead of Vector class.

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-js-module-v2#68]
```
spawn(pos: altShared.Vector3, // should accept altShared.IVector3
```
```
interface ColShapeCircleCreateOptions {
  pos: Vector2; // needs to be IVector2
```

Currently we need to create a new vector object from { x, y, z } object just to pass it to the altV API.

**Comment by xLuxy** [comment]
Changed in https://github.com/altmp/altv-js-module-v2/commit/068770e0105b0a6265037d46797b246be9f98709
