### ISSUE TITLE
Factory.create() should throw an error instead of returning null in case it fails.

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-js-module-v2#69]
`null` requires refactoring of the code from exception handling to null handling and it doesn't provide any info why the call failed, e.g. when creating a Vehicle with invalid model, the exception tells that, the `null` doesn't.

**Comment by LeonMrBonnie** [comment]
This is a bug, I fucked up the try catch

**Comment by LeonMrBonnie** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/6648c377c8b5a7fc2352e2d0385dab1c42b4b84a
