### ISSUE TITLE
VirtualGroupCreateOptions should accept maxEntitiesInStream, not streamingRangeLimit 

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-js-module-v2#70]
streamRange is set on VirtualEntity itself, not VirtualEntityGroup. v1 takes in `maxEntitiesInStream` param when creating VirtualEntityGroup.

**Comment by xLuxy** [comment]
Changed in https://github.com/altmp/altv-js-module-v2/commit/cfccd9667cf1e663c2e9edc4058a7e9f7b95461b
