### ISSUE TITLE
feat: specific meta handlers (client)

### ISSUE THREAD

**Issue by notmatical** [altmp/altv-js-module-v2#81]
I'm suggesting to add a meta change handler for a specified meta variable. Currently it is not performant in most cases to people who wish to listen to multiple meta changes in a class, currently you have to do key checks for the ones you actually want.

addMetaChange
addSyncedMetaChange
...etc

Whenever the variable is changed, in this case `myVariable` or `myClientVariable` these functions will be triggered with entity, value and oldValue

```ts
class TestClass {
    constructor() {
        alt.addSyncedMetaChange('myVariable', this.variableHandler.bind(this));
        alt.addMetaChange('myClientVariable', this.clientHandler.bind(this));
    }

    variableHandler(entity: alt.Entity, value: any, oldValue: any) {
        // ...
    }

    clientHandler(entity: alt.Entity, value: any, oldValue: any) {
        // ...
    }
}
```

**Comment by LeonMrBonnie** [comment]
This is something that can easily just be added to `alt.Utils` via the JS bindings.

**Comment by xLuxy** [comment]
Added in https://github.com/altmp/altv-js-module-v2/commit/603ccc8f0ab865efc517efbc4cac23b883127d07
