### ISSUE TITLE
Overriding globalThis.setTimeout causes issues with 3rd party node libraries.

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-js-module-v2#87]
```
[05:19:37][Error] Uncaught exception: Error: Expected a Timeout as first argument
    at globalThis.clearTimeout (internal:shared/timers.js:201:46)
    at Object.clearTimeout (file:///C:/Users/stani/projects/yolo/resources/main/server.js:1962:39)
```
Would be nice to not override nodejs apis xd

**Comment by xLuxy** [comment]
Basically: when only importing `@altv/shared`, all stuff registered within `@altv/shared` are not available. The namespaces (eg. `alt.Timers`) are empty objects. Played around a little bit but i'm unsure wheter or not that's the right solution - see https://github.com/altmp/altv-js-module-v2/commit/1078f4aee2996abf62f721b5edde56abe7d0e5f6

**Comment by xLuxy** [comment]
How did you call the `clearInterval` method. Please provide reproduction for this.

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/734ab0aab7cdc3b29be5030a6d0317cccecb5d03
