### ISSUE TITLE
player object is not available in onPlayerDisconnect

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-js-module-v2#90]
![image](https://github.com/altmp/altv-js-module-v2/assets/9081457/e39c2617-e58e-4f19-a77c-3a2a81840cce)
![image](https://github.com/altmp/altv-js-module-v2/assets/9081457/998aec43-35b3-495c-a993-387cfc1a0f0c)

**Comment by FlorianV85** [comment]
I have the same error with the player argument on several events requiring the player. It doesn't happen the first time, but after a reconnection.

**Comment by LeonMrBonnie** [comment]
I just reconnected a few times and it worked fine, please try to make a minimal reproduction resource

**Comment by LeonMrBonnie** [comment]
fixed
