### ISSUE TITLE
v2 entity creation performance degradation compared to v1

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-js-module-v2#92]
## v1
![image](https://github.com/altmp/altv-js-module-v2/assets/9081457/dfb112c6-36e4-4632-ab53-9e0b9699ddd8)
10k - 28ms
20k - 55ms
30k - 81ms
40k - 110ms

## v2
![image](https://github.com/altmp/altv-js-module-v2/assets/9081457/642f4b96-e7a0-4644-b6c1-5cc85c902985)
10k - 1s
20k - 5s
30k - 10s
40k - 18s

**Comment by LeonMrBonnie** [comment]
I investigated this a bit and this is definitely a deeper issue. Apparently you have to be very careful with what v8 APIs you use, as some of them are a lot slower than others.

E.g.
```cpp
v8::Local<v8::Context> ctx = obj->CreationContext();
v8::Isolate* isolate = ctx->GetIsolate();
```
is about twice as slow as doing
```
v8::Isolate* isolate = v8::Isolate::GetCurrent();
v8::Local<v8::Context> ctx = isolate->GetEnteredOrMicrotaskContext();
```
does this make any sense? No.

**Comment by LeonMrBonnie** [comment]
I profiled this a bit and curiously, half of the time is already spent in just calling the SDK function for creating virtual entities.
```cpp
Profiler::Sample sample("SDK_CreateVirtualEntity");
entity = alt::ICore::Instance().CreateVirtualEntity(group, pos, streamingDistance, data);
```
```
[20:25:49][Warning] SDK_CreateVirtualEntity | Total: 615983000ns (615ms) | Average: 61598ns (0ms) | Min: 5600ns (0ms) | Max: 1988300ns (1ms) | Samples: 10000
```
But there is definitely some improvements to be made to how ScriptObject's are stored and accessed (which is the other half of the ~1100ms)
But it's still very weird that somehow calling that SDK functions takes 600ms for 10k times in v2, but almost nothing in v1 xd

**Comment by LeonMrBonnie** [comment]
The call to the SDK taking so long is due to sync code being called there that also calls into the module, so ignore the confusion there. 
By reworking the script object storage, the time for creating 10k entities went down from ~1100ms to ~100ms, which is a good enough improvement. Other improvements to performance will be done in the future.
