### ISSUE TITLE
Some natives straight up fails

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-js-module-v2#95]
![image](https://github.com/altmp/altv-js-module-v2/assets/9081457/deba87f2-8980-42a4-9f60-153d77ad0602)
![image](https://github.com/altmp/altv-js-module-v2/assets/9081457/445d91d1-d153-4e7d-ae28-24714a99864b)
Works on v1.

**Comment by LeonMrBonnie** [comment]
Fixed
