### ISSUE TITLE
game.getAmmoInClip doesn't work

### ISSUE THREAD

**Issue by Yiin** [altmp/altv-js-module-v2#98]
![image](https://github.com/altmp/altv-js-module-v2/assets/9081457/bd689c43-10a1-450a-a4dd-b9d842c864eb)

```ts
const [, gameClip] = game.getAmmoInClip(player, hash)
```

I'm calling it inside random callback (neither timer not event).

**Comment by xLuxy** [comment]
Fixed in https://github.com/altmp/altv-js-module-v2/commit/a632e534b1613f38b5c78c17a382eb2f657091d9
